name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      STAGE: dev  
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: adding-cdk.json

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Enable corepack
        run: corepack enable

      - name: Install specific version of pnpm
        run: corepack prepare pnpm@8.9.0 --activate

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build, Lint, and Test
        run: make all

      - name: Run cowsay
        run: |
          pnpm install cowsay
          pnpm exec cowsay "CI pipeline complete!"
        
